version: "1"

services:
  postgres:
    image: postgres:12
    volumes:
      - ./data:/var/lib/postgresql/data/:rw
    environment:
      - POSTGRES_INITDB_WALDIR=/var/log/pg_logs
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  parser:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python main.py
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/sergek_meteo_parser

      